#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : latexcodec
Version  : 1.0.7
Release  : 6
URL      : https://files.pythonhosted.org/packages/c7/5c/00275a2b575d1e3a30fbe6a7cd8fadd391010a0e7cd8e484c8c0be9a6ab0/latexcodec-1.0.7.tar.gz
Source0  : https://files.pythonhosted.org/packages/c7/5c/00275a2b575d1e3a30fbe6a7cd8fadd391010a0e7cd8e484c8c0be9a6ab0/latexcodec-1.0.7.tar.gz
Summary  : A lexer and codec to work with LaTeX code in Python.
Group    : Development/Tools
License  : MIT
Requires: latexcodec-license = %{version}-%{release}
Requires: latexcodec-python = %{version}-%{release}
Requires: latexcodec-python3 = %{version}-%{release}
Requires: six
BuildRequires : buildreq-distutils3

%description
latexcodec
==========
|travis| |coveralls|
A lexer and codec to work with LaTeX code in Python.

%package license
Summary: license components for the latexcodec package.
Group: Default

%description license
license components for the latexcodec package.


%package python
Summary: python components for the latexcodec package.
Group: Default
Requires: latexcodec-python3 = %{version}-%{release}

%description python
python components for the latexcodec package.


%package python3
Summary: python3 components for the latexcodec package.
Group: Default
Requires: python3-core

%description python3
python3 components for the latexcodec package.


%prep
%setup -q -n latexcodec-1.0.7

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1556893684
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/latexcodec
cp LICENSE.rst %{buildroot}/usr/share/package-licenses/latexcodec/LICENSE.rst
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/latexcodec/LICENSE.rst

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
