#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : latexcodec
Version  : 2.0.0
Release  : 9
URL      : https://files.pythonhosted.org/packages/bc/cf/ead5e88a8cf2e66c673b1871ee78012d8b2ea9ce5ac85e441ef66790c418/latexcodec-2.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/bc/cf/ead5e88a8cf2e66c673b1871ee78012d8b2ea9ce5ac85e441ef66790c418/latexcodec-2.0.0.tar.gz
Summary  : A lexer and codec to work with LaTeX code in Python.
Group    : Development/Tools
License  : MIT
Requires: latexcodec-license = %{version}-%{release}
Requires: latexcodec-python = %{version}-%{release}
Requires: latexcodec-python3 = %{version}-%{release}
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : six

%description
latexcodec
==========
|travis| |codecov|
A lexer and codec to work with LaTeX code in Python.

%package license
Summary: license components for the latexcodec package.
Group: Default

%description license
license components for the latexcodec package.


%package python
Summary: python components for the latexcodec package.
Group: Default
Requires: latexcodec-python3 = %{version}-%{release}

%description python
python components for the latexcodec package.


%package python3
Summary: python3 components for the latexcodec package.
Group: Default
Requires: python3-core

%description python3
python3 components for the latexcodec package.


%prep
%setup -q -n latexcodec-2.0.0
cd %{_builddir}/latexcodec-2.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1579030591
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/latexcodec
cp %{_builddir}/latexcodec-2.0.0/LICENSE.rst %{buildroot}/usr/share/package-licenses/latexcodec/bf6d8a42dc765282b741834f130d0b24e2b47908
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/latexcodec/bf6d8a42dc765282b741834f130d0b24e2b47908

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
